Fuel Rod:
	#Base heat production per second of a fuel
	Base Heat Production: 1
	
	#The maximum heat capacity of a fuel rod before it melts down
	Heat Capacity: 200
	
	#The heat before a meltdown destroys the fuel rod with lava
	Meltdown Heat Capacity: 1000
	
	#The amount of heat removed by a block of water near to a core
	Water Heat Reduction: 0.5
	
	#Amount a nearby lava source increases reactor temperature production
	Lava Source Bonus: 1.1
	
	#Amount a nearby fire source increases reactor temperature
	Fire Source Bonus: 5
	
	#Amount a water block reduces the temperature of a rod
	Water Heat Reduction: 0.8
	
	#Chance of melting glass during a meltdown (per tick)
	Glass Melt Chance: 0.005
	
	#Multiplier a block of iron applies to heat production
	Iron Damp Multiplier: 0.6
	
	#Multiplier a block of sand applies to heat production
	Sand Damp Multiplier: 0.75
	
	#The amount of heat in the reactor a piece of ice can take
	Ice Heat Reduction: 10
	
	#The percentage of Heat capacity below which the rod is breakable
	Allow Destruction Temperature Threshold: 0.25
	
Heat:
	#The range over which heat spreads and water has a cooling affect
	Range: 4
	
	#The heat value above which wood is ignited
	Wood Ignition Threshold: 5
	
	#The chance per tick wood above the threshold will set on fire
	Wood Ignition Chance: 0.1
	
	#The temperature required to evaporate water
	Water Evaporation Threshold: 10
	
	#Wool/cable ignition threshold
	Cable Ignition Threshold: 900
	
	#Wool/cable ignition threshold
	Cable Ignition Chance: 0.01

Mining Rig:
	#The number of ticks between mining head movements
	Move Ticks: 1

	#Temperature above which glass smashes
	Glass Break Threshold: 850
	
	#The chance per tick glass above the threshold will smash
	Glass Break Chance: 0.1
	
	#The temperature above which ice melts
	Ice Melt Threshold: 50

Mining Rig:
	#The number of ticks between mining head movements
	Move Ticks: 1

Core:
	#Ticks between sign updates
	Sign Update Ticks: 20
